# Generated by Django 3.2.6 on 2021-09-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_pet_id'),
        ('Advertisment', '0005_auto_20200929_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='house',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
        ),
    ]
