# Generated by Django 3.2.7 on 2021-10-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_type', models.CharField(max_length=200)),
                ('Patient_owner_name', models.CharField(max_length=200)),
                ('patient_owner_phone_no', models.IntegerField(blank=True)),
                ('pet_age', models.CharField(max_length=200)),
                ('pet_gender', models.CharField(max_length=200)),
                ('pet_problem', models.TextField(blank=True)),
            ],
        ),
    ]
