# Generated by Django 3.1.1 on 2021-10-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctor_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_form',
            name='date_time',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
